const actionTypes = {
  LOAD_WORKOUT: 'LOAD_WORKOUT',
  LOAD_WORKOUT_ERROR: 'LOAD_WORKOUT_ERROR',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  UPDATE_WORKOUT_ERROR: 'UPDATE_WORKOUT_ERROR'
}

export default actionTypes
