export interface actionTypesInterface {
  LOAD_WORKOUT: string
  LOAD_WORKOUT_ERROR: string
  WORKOUT_LOADING: string
  UPDATE_WORKOUT: string
  UPDATE_WORKOUT_ERROR: string
  LOAD_SCHEDULES: string
  LOAD_SCHEDULES_ERROR: string
  SCHEDULES_LOADING: string
  UPDATE_SESSION: string
  UPDATE_SESSION_ERROR: string
  CREATE_SESSION: string
  CREATE_SESSION_ERROR: string
  DELETE_SESSION: string
  DELETE_SESSION_ERROR: string
  USER_LOGIN: string,
  USER_LOGIN_ERROR: string,
  USER_LOGOUT: string
  USER_LOGOUT_ERROR: string
  LOAD_SCHEDULE: string
  LOAD_SCHEDULE_ERROR: string
  ADD_OR_REMOVE_SESSION: string
  ADD_OR_REMOVE_SESSION_ERROR: string
  LOAD_PROGRAMS: string
  LOAD_PROGRAMS_ERROR: string
  UPDATE_PROGRAM: string
  UPDATE_PROGRAM_ERROR: string
  DELETE_PROGRAM: string
  DELETE_PROGRAM_ERROR: string
  LOAD_USERS: string
  LOAD_USERS_ERROR: string
  CREATE_PROGRAM:string
  CREATE_PROGRAM_ERROR:string
}

const actionTypes: actionTypesInterface = {
  LOAD_WORKOUT: 'LOAD_WORKOUT',
  LOAD_WORKOUT_ERROR: 'LOAD_WORKOUT_ERROR',
  WORKOUT_LOADING: 'WORKOUT_LOADING',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  UPDATE_WORKOUT_ERROR: 'UPDATE_WORKOUT_ERROR',
  LOAD_SCHEDULES: 'LOAD_SCHEDULES',
  LOAD_SCHEDULES_ERROR: 'LOAD_SCHEDULES_ERROR',
  SCHEDULES_LOADING: 'SCHEDULES_LOADING',
  UPDATE_SESSION: 'UPDATE_SESSION',
  UPDATE_SESSION_ERROR: 'UPDATE_SESSION_ERROR',
  CREATE_SESSION: 'CREATE_SESSION',
  CREATE_SESSION_ERROR: 'CREATE_SESSION_ERROR',
  DELETE_SESSION: 'DELETE_SESSION',
  DELETE_SESSION_ERROR: 'DELETE_SESSION_ERROR',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',
  LOAD_SCHEDULE: 'LOAD_SCHEDULE',
  LOAD_SCHEDULE_ERROR: 'LOAD_SCHEDULE_ERROR',
  ADD_OR_REMOVE_SESSION: 'ADD_OR_REMOVE_SESSION',
  ADD_OR_REMOVE_SESSION_ERROR: 'ADD_OR_REMOVE_SESSION_ERROR',
  LOAD_PROGRAMS: 'LOAD_PROGRAMS',
  LOAD_PROGRAMS_ERROR: 'LOAD_PROGRAMS_ERROR',
  UPDATE_PROGRAM: 'UPDATE_PROGRAM',
  UPDATE_PROGRAM_ERROR: 'UPDATE_PROGRAM_ERROR',
  DELETE_PROGRAM: 'DELETE_PROGRAM',
  DELETE_PROGRAM_ERROR: 'DELETE_PROGRAM_ERROR',
  CREATE_PROGRAM: 'CREATE_PROGRAM',
  CREATE_PROGRAM_ERROR: 'CREATE_PROGRAM_ERROR',
  LOAD_USERS: 'LOAD_USERS',
  LOAD_USERS_ERROR: 'LOAD_USERS_ERROR'
}

export default actionTypes
