export interface actionTypesInterface {
  LOAD_WORKOUT: string
  LOAD_WORKOUT_ERROR: string
  WORKOUT_LOADING: string
  UPDATE_WORKOUT: string
  UPDATE_WORKOUT_ERROR: string
  LOAD_SCHEDULES: string
  LOAD_SCHEDULES_ERROR: string
  SCHEDULES_LOADING: string
  UPDATE_SESSION: string
  UPDATE_SESSION_ERROR: string
  CREATE_SESSION: string
  CREATE_SESSION_ERROR: string
  USER_LOGIN: string,
  USER_LOGIN_ERROR: string,
  USER_LOGOUT: string
  USER_LOGOUT_ERROR: string
  LOAD_SCHEDULE: string
  LOAD_SCHEDULE_ERROR: string
}

const actionTypes: actionTypesInterface = {
  LOAD_WORKOUT: 'LOAD_WORKOUT',
  LOAD_WORKOUT_ERROR: 'LOAD_WORKOUT_ERROR',
  WORKOUT_LOADING: 'WORKOUT_LOADING',
  UPDATE_WORKOUT: 'UPDATE_WORKOUT',
  UPDATE_WORKOUT_ERROR: 'UPDATE_WORKOUT_ERROR',
  LOAD_SCHEDULES: 'LOAD_SCHEDULES',
  LOAD_SCHEDULES_ERROR: 'LOAD_SCHEDULES_ERROR',
  SCHEDULES_LOADING: 'SCHEDULES_LOADING',
  UPDATE_SESSION: 'UPDATE_SESSION',
  UPDATE_SESSION_ERROR: 'UPDATE_SESSION_ERROR',
  CREATE_SESSION: 'CREATE_SESSION',
  CREATE_SESSION_ERROR: 'CREATE_SESSION_ERROR',
  USER_LOGIN: 'USER_LOGIN',
  USER_LOGIN_ERROR: 'USER_LOGIN_ERROR',
  USER_LOGOUT: 'USER_LOGOUT',
  USER_LOGOUT_ERROR: 'USER_LOGOUT_ERROR',
  LOAD_SCHEDULE: 'LOAD_SCHEDULE',
  LOAD_SCHEDULE_ERROR: 'LOAD_SCHEDULE_ERROR'
}

export default actionTypes
